executable   = /home/lroy02/acceleration_project/run.sh
arguments    = "/home/lroy02/acceleration_project/config.ini /home/lroy02/acceleration_project/inference.hdf"

error        = error_GW150914.txt
log          = log_GW150914.txt
output = out_GW150914.txt
getenv = True

universe = vanilla
request_cpus = 10
request_disk =  5000
request_memory = 5000

should_transfer_files = yes
when_to_transfer_output = on_exit

queue
