executable   = /home/lroy02/PE/acc_sig_zero-acc_temp/PE.sh
arguments    = "/home/lroy02/PE/acc_sig_zero-acc_temp/marg_inj.ini /home/lroy02/PE/acc_sig_zero-acc_temp/output.hdf"


error        = error.txt
log          = log.txt
output = out.txt
getenv = True

universe = vanilla
request_cpus = 16
request_disk =  5000
request_memory = 5000

should_transfer_files = yes
when_to_transfer_output = on_exit
queue
