executable = run_plot.sh
arguments = $(filename)
output = logs/$(filename).out
error  = logs/$(filename).err
log    = logs/$(filename).log
request_cpus = 1
request_memory = 4GB
request_disk = 2GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/lroy02/ground_based_acc/project/workflow/main_workflow/workflow_outputs/local-site-scratch/work/$(filename)
queue filename from file_list.txt
